export const TOP_CITIES: { name: string; insee: string; slug: string }[] = [
  { name: 'Paris', insee: '75056', slug: 'paris' },
  { name: 'Marseille', insee: '13055', slug: 'marseille' },
  { name: 'Lyon', insee: '69123', slug: 'lyon' },
  { name: 'Toulouse', insee: '31555', slug: 'toulouse' },
  { name: 'Nice', insee: '06088', slug: 'nice' },
  { name: 'Nantes', insee: '44109', slug: 'nantes' },
  { name: 'Montpellier', insee: '34172', slug: 'montpellier' },
  { name: 'Strasbourg', insee: '67482', slug: 'strasbourg' },
  { name: 'Bordeaux', insee: '33063', slug: 'bordeaux' },
  { name: 'Lille', insee: '59350', slug: 'lille' },
  { name: 'Rennes', insee: '35238', slug: 'rennes' },
  { name: 'Reims', insee: '51454', slug: 'reims' },
  { name: 'Toulon', insee: '83137', slug: 'toulon' },
  { name: 'Saint-Étienne', insee: '42218', slug: 'saint-etienne' },
  { name: 'Le Havre', insee: '76351', slug: 'le-havre' },
  { name: 'Grenoble', insee: '38185', slug: 'grenoble' },
  { name: 'Dijon', insee: '21231', slug: 'dijon' },
  { name: 'Angers', insee: '49007', slug: 'angers' },
  { name: 'Nîmes', insee: '30189', slug: 'nimes' },
  { name: 'Clermont-Ferrand', insee: '63113', slug: 'clermont-ferrand' },
]
